import {useEffect,useRef,useState} from 'react';
import {BALANCE,DEEP_BOSSES,BUFFS,CLASSES,DEEP_FLOORS} from './data';
import {activeSynergies,advance,applyReward,applyStartingBuff,buyShop,heroFor,initial,load,loadEarned,rerollRewards,save,saveEarned,shopCosts,shopOffer,startingBuffChoices,tick} from './engine';
import type{ClassId,Item,RunState}from'./types';
import {achievements} from './config/achievements';
import {submitRun,fetchLeagueState,postAchievement,syncMetaProgression,fetchRemoteMeta} from './api';
import {CLASS_SPRITES,ENEMY_SPRITES,SPRITE_CREDIT} from './sprites';
import {runBalanceSimulation,type SimReport} from './balanceSimulator';
import {applyMetaBonuses,awardMetaForRun,loadMeta,metaBonuses,saveMeta,xpToNextMetaLevel} from './metaProgression';

const fmt=(seconds:number)=>`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
export default function App(){const[run,setRun]=useState<RunState>(()=>load()||initial);const[meta,setMeta]=useState(()=>loadMeta());const[name,setName]=useState('');const[debug,setDebug]=useState(true);const[tab,setTab]=useState<'expedition'|'loadout'|'log'>('expedition');const[simReport,setSimReport]=useState<SimReport|null>(null);const[simRunning,setSimRunning]=useState(false);const[metaAward,setMetaAward]=useState<any>(null);
 useEffect(()=>{const id=setInterval(()=>setRun(s=>tick(s)),BALANCE.tickMs);return()=>clearInterval(id)},[]);useEffect(()=>save(run),[run]);
 useEffect(()=>{fetchRemoteMeta(meta.playerId).then(remote=>{if(remote){const next={...meta,...remote,playerId:meta.playerId};setMeta(next);saveMeta(next)}})},[]);
 const submitted=useRef<number|null>(null);const[submitState,setSubmitState]=useState<'idle'|'sending'|'saved'|'offline'>('idle');
 useEffect(()=>{if(run.screen==='summary'&&run.hero&&submitted.current!==run.seed){submitted.current=run.seed;setSubmitState('sending');submitRun(run).then(r=>setSubmitState(r?.persisted?'saved':'offline'));}},[run.screen,run.seed]);
 const metaSubmitted=useRef<number|null>(null);
 useEffect(()=>{if(run.screen==='summary'&&run.hero&&metaSubmitted.current!==run.seed){metaSubmitted.current=run.seed;const result=awardMetaForRun(meta,run);setMeta(result.meta);setMetaAward(result.award);saveMeta(result.meta);syncMetaProgression(result.meta,run,result.award);}},[run.screen,run.seed]);
 const[earned,setEarned]=useState<string[]>(()=>loadEarned());
 useEffect(()=>{if(!run.hero)return;const fresh=run.achievements.filter(id=>!earned.includes(id));if(!fresh.length)return;const next=[...earned,...fresh];setEarned(next);saveEarned(next);const who=run.hero.name;fresh.forEach(id=>postAchievement(who,id));},[run.achievements.length]);
 const chooseClass=(id:ClassId)=>setRun(s=>({...s,hero:applyMetaBonuses(heroFor(name.trim()||meta.managerName||'Anonymous Menace',id),meta),maxFloor:meta.unlockedDepth,screen:'buff'}));
 const startBuff=(b:typeof BUFFS[number])=>setRun(s=>applyStartingBuff(s,b));
 if(run.screen==='menu')return <Shell onNav={screen=>setRun({...run,screen})}><div className="hero"><div className="crest">D<span>XL</span></div><p className="eyebrow">A fantasy league roguelite</p><h1>THE DESCENT</h1><p className="lede">Clear Floor 18. Then push deeper with permanent meta progression.</p><button className="primary" onClick={()=>{setMetaAward(null);setRun({...initial,screen:'name',seed:Date.now(),maxFloor:meta.unlockedDepth})}}>Begin the descent <b>→</b></button>{load()?.hero&&<button className="ghost" onClick={()=>setRun(load()!)}>Continue run · Floor {load()!.floor}</button>}<button className="ghost" onClick={()=>setRun({...run,screen:'meta'})}>Meta progression · Lv. {meta.level}</button><p className="fine">AUTO-BATTLE · PERMADEATH · LONG-TERM PUSH</p></div></Shell>;
 if(run.screen==='achievements')return <Shell onNav={screen=>setRun({...run,screen})}><AchievementsPage earned={earned}/></Shell>;
 if(run.screen==='league')return <Shell onNav={screen=>setRun({...run,screen})}><LeagueHub/></Shell>;
 if(run.screen==='meta')return <Shell onNav={screen=>setRun({...run,screen})}><MetaPage meta={meta}/></Shell>;
 if(run.screen==='settings')return <Shell onNav={screen=>setRun({...run,screen})}><InfoPage eyebrow="Accessibility & saves" title="Settings" intro="Your expedition autosaves locally after every state change."><div className="settingsCard"><label><span>Reduced motion</span><input type="checkbox" onChange={e=>document.documentElement.classList.toggle('reduced',e.target.checked)}/></label><label><span>Balance telemetry</span><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/></label><button className="danger" onClick={()=>{localStorage.removeItem('descent.run');setRun(initial)}}>Reset local save</button></div></InfoPage></Shell>;
 if(run.screen==='name')return <Shell><Setup step="01 / 03" title="Name your manager" sub="This will be carved into the leaderboard—or the injury report."><input autoFocus maxLength={24} placeholder="Manager name" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&name.trim()&&setRun({...run,screen:'class'})}/><button className="primary" disabled={!name.trim()} onClick={()=>setRun({...run,screen:'class'})}>Choose your class →</button></Setup></Shell>;
 if(run.screen==='class')return <Shell><Setup step="02 / 03" title="Choose your archetype" sub="Your class shapes the build. The dungeon shapes your obituary."><div className="classGrid">{Object.entries(CLASSES).map(([id,c])=><button className="classCard" key={id} onClick={()=>chooseClass(id as ClassId)}><img src={CLASS_SPRITES[id as ClassId]} alt=""/><div><h3>{c.name}</h3><small>{c.tag}</small><p>{c.desc}</p><em>{c.ability}</em></div></button>)}</div></Setup></Shell>;
 if(run.screen==='buff')return <Shell><Setup step="03 / 03" title="Pick your opening edge" sub="Three class-weighted offers are drafted fresh every run."><div className="buffGrid">{startingBuffChoices(run.seed,run.hero!.classId).map((b,i)=><button className={`buffCard perk-${b.rarity?.toLowerCase()}`} key={b.title} onClick={()=>startBuff(b)}><span>0{i+1} · {b.rarity}</span><h3>{b.title}</h3><p>{b.detail}</p><b>Take this edge →</b></button>)}</div></Setup></Shell>;
 if(run.screen==='reward'){const h=run.hero!;const cost=shopCosts(run.floor);const offer=shopOffer(run);return <GameFrame run={run} tab={tab} setTab={setTab}><section className="reward"><p className="eyebrow">Checkpoint secured</p><h2>Choose what survives with you</h2><p>The rest goes back on waivers. Then spend your gold before it spends you.</p><CheckpointSnapshot hero={h}/><div className="rewardGrid">{run.rewards.map(r=><button key={r.id} className={`rewardCard ${r.item?.rarity||''}`} onClick={()=>setRun(applyReward(run,r))}><span>{r.item?.rarity||'BUILD REWARD'}</span><div className="rewardIcon">{r.item?.rarity==='Mythic'?'✺':r.item?.rarity==='Legendary'?'♛':r.kind==='gear'?'◇':r.kind==='heal'?'✚':r.kind==='defense'?'⬡':'↗'}</div><h3>{r.title}</h3><p>{r.detail}</p>{r.item?.curse&&<em className="curseTag">CURSE · {r.item.curse}</em>}<b>Claim reward</b></button>)}</div><button className="reroll" disabled={!h.rerolls} onClick={()=>setRun(rerollRewards(run))}>⟳ Reroll rewards ({h.rerolls})</button><aside className="shop"><header><div><p className="eyebrow">The between-period shop</p><h3>Spend it or die rich</h3></div><b>◈ {h.gold} gold</b></header><div className="shopGrid"><button disabled={h.gold<cost.heal||h.hp>=h.maxHp} onClick={()=>setRun(buyShop(run,'heal'))}><span>✚</span><div><b>Bench Medic</b><small>Restore 28% HP</small></div><em>{cost.heal}g</em></button><button disabled={h.gold<cost.reroll} onClick={()=>setRun(buyShop(run,'reroll'))}><span>⟳</span><div><b>Waiver Token</b><small>+1 reroll</small></div><em>{cost.reroll}g</em></button><button className={`shopItem ${offer.rarity}`} disabled={h.gold<cost.item} onClick={()=>setRun(buyShop(run,'item'))}><span>◇</span><div><b>{offer.name}</b><small>{offer.rarity} {offer.slot}{offer.set?` · ${offer.set} set`:''}</small><ItemMeta item={offer}/></div><em>{cost.item}g</em></button></div></aside></section></GameFrame>;}
 if(run.screen==='summary')return <Shell onNav={screen=>setRun({...run,screen})}><div className="summary"><p className="eyebrow">Run {run.won?'cleared':'complete'}</p><h1>{run.won?'The deep chart is broken.':'Mathematically eliminated.'}</h1><div className="summaryStats"><span>Manager<b>{run.hero?.name}</b></span><span>Class<b>{run.hero&&CLASSES[run.hero.classId].name}</b></span><span>Floor reached<b>{run.floor} / {run.maxFloor||18}</b></span><span>Run time<b>{fmt(run.telemetry.elapsed)}</b></span></div><p>{run.won?'The Depth Chart Devourer has been overruled. Your permanent file got heavier.':`Your projections ended in ${DEEP_FLOORS[run.floor-1]||'the descent'}. The waiver wire offers no condolences.`}</p>{metaAward&&<MetaAward award={metaAward}/>}<p className="fine">{submitState==='sending'?'Submitting to the league…':submitState==='saved'?'Logged to the league leaderboard.':submitState==='offline'?'League offline — run saved locally only.':''}</p><button className="primary" onClick={()=>{localStorage.removeItem('descent.run');setMetaAward(null);setRun({...initial,screen:'name',seed:Date.now(),maxFloor:meta.unlockedDepth})}}>Descend again →</button><button className="ghost" onClick={()=>setRun({...initial,screen:'meta'})}>View meta progression</button></div></Shell>;
 const h=run.hero!,e=run.enemy!;const playerDps=h.attack*h.speed*(1+h.crit*.7)+(h.attack*2.25/8);const enemyDps=Math.max(1,e.attack*100/(100+h.defense*7))*e.speed;const ttk=e.hp/playerDps, survival=(h.hp+h.shield)/enemyDps;
 return <GameFrame run={run} tab={tab} setTab={setTab}><main className="battle"><section className="floorHead"><div><p className="eyebrow">Floor {String(run.floor).padStart(2,'0')} · Encounter {run.encounter}/{BALANCE.encountersPerFloor}</p><h2>{DEEP_FLOORS[run.floor-1]}</h2><p>{run.floor>18?'Meta push territory. Mistakes compound.':'Where projections come to become regrets.'}</p></div><div className="floorPips">{DEEP_FLOORS.slice(0,run.maxFloor||18).map((_,i)=><i key={i} className={i<run.floor?'done':i===run.floor-1?'now':''}/>)}</div></section>
 <section className="arena"><Combatant side="hero" icon={CLASSES[h.classId].icon} sprite={CLASS_SPRITES[h.classId]} name={h.name} subtitle={CLASSES[h.classId].name} hp={h.hp} max={h.maxHp} shield={h.shield}/><div className="versus"><b>VS</b><span>{fmt(run.telemetry.encounterElapsed)}</span></div><Combatant side="enemy" icon={e.boss?'♛':'☠'} sprite={ENEMY_SPRITES[e.name]} name={e.name} subtitle={e.boss?'Floor boss · Elite':'Dungeon resident'} hp={e.hp} max={e.maxHp}/></section>
 {e.boss&&<aside className="warning"><b>⚠ {DEEP_BOSSES[run.floor]?.mechanic}</b><span>{DEEP_BOSSES[run.floor]?.intro}</span></aside>}
 <section className="lower"><div className="ability"><div className="abilityIcon">{CLASSES[h.classId].icon}</div><div><small>AUTOMATIC ABILITY</small><h3>{CLASSES[h.classId].ability.split(':')[0]}</h3><p>{CLASSES[h.classId].ability.split(':')[1]}</p></div><div className="cooldown"><span style={{'--p':`${Math.min(100,run.abilityClock/8*100)}%`} as React.CSSProperties}/><b>{Math.max(0,8-run.abilityClock).toFixed(1)}s</b></div></div><div className="log"><header><b>Combat feed</b><span>LIVE</span></header>{run.log.slice(0,5).map((l,i)=><p key={i} className={l.includes('⚠')?'alert':''}>{l}</p>)}</div></section>
 {debug&&<section className="debug"><header><b>⌁ Balance telemetry</b><button onClick={()=>setDebug(false)}>×</button></header><div>{[['Player DPS',playerDps.toFixed(1)],['Enemy DPS',enemyDps.toFixed(1)],['Est. time to kill',`${ttk.toFixed(1)}s`],['Est. survival',`${survival.toFixed(1)}s`],['Run duration',fmt(run.telemetry.elapsed)],['Recent damage',String(run.telemetry.damage.reduce((a,b)=>a+b,0))],['Recent healing',String(run.telemetry.healing.reduce((a,b)=>a+b,0))],['Difficulty',`${(Math.pow(1+BALANCE.enemyAttackPerFloor,run.floor-1)*100).toFixed(0)}%`]].map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div><BalanceSim report={simReport} running={simRunning} onRun={()=>{setSimRunning(true);window.setTimeout(()=>{setSimReport(runBalanceSimulation(10));setSimRunning(false)},25)}}/></section>}
 </main></GameFrame>;
}
function BalanceSim({report,running,onRun}:{report:SimReport|null;running:boolean;onRun:()=>void}){return <aside className="simPanel"><header><div><small>DEV SIMULATOR</small><b>Class balance probe</b></div><button disabled={running} onClick={onRun}>{running?'Running…':'Run 60 sims'}</button></header>{report?<><div className="simSummary"><span><small>Clear rate</small><b>{Math.round(report.clearRate*100)}%</b></span><span><small>Avg floor</small><b>{report.averageFloor.toFixed(1)}</b></span><span><small>Avg time</small><b>{fmt(report.averageSeconds)}</b></span><span><small>Runs</small><b>{report.runs}</b></span></div><table><thead><tr><th>Class</th><th>Clear</th><th>Avg floor</th><th>Avg time</th><th>Deaths</th></tr></thead><tbody>{report.classes.map(c=><tr key={c.classId}><td>{c.className}</td><td>{Math.round(c.clearRate*100)}%</td><td>{c.averageFloor.toFixed(1)}</td><td>{fmt(c.averageSeconds)}</td><td>{c.deathFloors}</td></tr>)}</tbody></table>{report.notes.length>0&&<ul>{report.notes.map(n=><li key={n}>{n}</li>)}</ul>}</>:<p>Runs competent auto-picks across all classes without touching the current save. Use this after item, class, boss, or scaling changes.</p>}</aside>}
function MetaAward({award}:{award:any}){return <div className="metaAward"><span><small>XP earned</small><b>+{award.xp}</b></span><span><small>Essence</small><b>+{award.essence}</b></span><span><small>Level ups</small><b>{award.levelUps}</b></span><span><small>Depth</small><b>{award.unlockedDepthAfter}</b></span></div>}
function MetaPage({meta}:{meta:ReturnType<typeof loadMeta>}){const b=metaBonuses(meta,'wizard');return <InfoPage eyebrow="Permanent file" title="Meta progression" intro="Offline-first account progression. Supabase sync is best-effort; local play always works."><div className="metaHero"><div><small>MANAGER LEVEL</small><b>{meta.level}</b><p>{meta.xp} XP · next target about {xpToNextMetaLevel(meta)} XP</p></div><div><small>DEEPEST UNLOCK</small><b>Floor {meta.unlockedDepth}</b><p>Floor 18 is the campaign clear. Floor 40 is the current push cap.</p></div><div><small>ESSENCE</small><b>{meta.essence}</b><p>Future upgrade currency. Currently earned and saved, spending comes next.</p></div></div><div className="placeholderGrid"><article><small>PERMANENT BONUSES</small><h3>Controlled power</h3><p>Current global bonuses include up to +{Math.round(b.attackPct*100)}% attack, +{b.maxHp} max HP, +{b.defense} defense, +{b.startingGold} starting gold, and +{b.rerolls} reroll.</p></article><article><small>CAREER</small><h3>{meta.lifetimeRuns} runs</h3><p>Best floor {meta.bestFloor}. Floor 18 clears: {meta.clears18}. Floor 40 clears: {meta.clears40}.</p></article><article><small>CLASS MASTERY</small><h3>Per-class growth</h3><p>Each class gains capped mastery XP after runs. Mastery adds small class-specific HP/attack scaling.</p></article><article><small>SYNC</small><h3>Supabase-ready</h3><p>Progress is saved locally first, then synced through Netlify Functions when the backend tables are installed.</p></article></div><h2 className="feedHead">Class mastery</h2><div className="metaClassGrid">{Object.entries(meta.classMastery).map(([id,m])=><article key={id}><small>{CLASSES[id as ClassId].name}</small><b>Lv. {m.level}</b><p>{m.xp} XP</p></article>)}</div></InfoPage>}
const itemStat=(i:Item)=>i.stat==='speed'?`+${Math.round(i.value*100)}% speed`:`+${i.value} ${i.stat}`;
function ItemMeta({item}:{item:Item}){return <p className="itemMeta"><strong>{itemStat(item)}</strong>{item.effect&&<span>{item.effect.description}</span>}{item.curse&&<span className="curseTag">CURSE · {item.curse}</span>}</p>}
function CheckpointSnapshot({hero}:{hero:RunState['hero']}){if(!hero)return null;return <aside className="checkpointSnapshot"><div className="snapshotStats"><span><small>Health</small><b>{Math.round(hero.hp)} / {hero.maxHp}</b></span><span><small>Shield</small><b>{hero.shield}</b></span><span><small>Attack</small><b>{hero.attack}</b></span><span><small>Defense</small><b>{hero.defense}</b></span><span><small>Speed</small><b>{hero.speed.toFixed(2)}</b></span><span><small>Crit</small><b>{Math.round(hero.crit*100)}%</b></span></div><div className="snapshotGear">{['Weapon','Helmet','Armor','Boots','Trinket','Relic'].map(slot=>{const item=hero.gear.find(i=>i.slot===slot);return <article key={slot} className={item?.rarity||''}><small>{slot}</small><b>{item?.name||'Empty'}</b><em>{item?itemStat(item):'—'}</em></article>})}</div></aside>}
function Shell({children,onNav}:{children:React.ReactNode;onNav?:(screen:'menu'|'achievements'|'settings'|'league'|'meta')=>void}){return <div className="shell"><header className="top"><button className="wordmark" onClick={()=>onNav?.('menu')}>THE <span>DESCENT</span></button><nav><button onClick={()=>onNav?.('achievements')}>Achievements</button><button onClick={()=>onNav?.('league')}>League Hub</button><button onClick={()=>onNav?.('meta')}>Meta</button><button onClick={()=>onNav?.('settings')}>Settings</button></nav></header>{children}<footer>NO PRIZES · NO MERCY · <a href={SPRITE_CREDIT.url} target="_blank" rel="noreferrer">SPRITES: {SPRITE_CREDIT.name} ({SPRITE_CREDIT.license})</a></footer></div>}
function InfoPage({eyebrow,title,intro,children}:{eyebrow:string;title:string;intro:string;children:React.ReactNode}){return <main className="infoPage"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p>{children}</main>}
function Setup({step,title,sub,children}:{step:string,title:string,sub:string,children:React.ReactNode}){return <div className="setup"><p className="eyebrow">Expedition setup · {step}</p><h1>{title}</h1><p>{sub}</p>{children}</div>}
function GameFrame({run,tab,setTab,children}:{run:RunState;tab:'expedition'|'loadout'|'log';setTab:(v:'expedition'|'loadout'|'log')=>void;children:React.ReactNode}){const newRun=()=>{if(!window.confirm('Abandon the current run and start a new one?'))return;localStorage.removeItem('descent.run');location.reload()};return <div className="game"><header className="gameTop"><b>THE <span>DESCENT</span></b><div className="runmeta"><span>Floor<b>{run.floor} / {run.maxFloor||18}</b></span><span>Encounter<b>{run.encounter} / {BALANCE.encountersPerFloor}</b></span><span>Run time<b>{fmt(run.telemetry.elapsed)}</b></span></div><div className="currencies"><span>◈ {run.hero?.gold}</span><span>✦ {run.hero?.essence}</span><span>⟳ {run.hero?.rerolls}</span></div><button className="newRunButton" onClick={newRun}>New run</button></header><nav className="tabs">{(['expedition','loadout','log'] as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>{tab==='expedition'?children:tab==='loadout'?<Loadout run={run}/>:<div className="fullLog"><h2>Expedition log</h2>{run.log.map((l,i)=><p key={i}>{l}</p>)}</div>}</div>}
function Combatant({side,icon,sprite,name,subtitle,hp,max,shield=0}:{side:string;icon:string;sprite?:string;name:string;subtitle:string;hp:number;max:number;shield?:number}){return <article className={`combatant ${side}`}><div className="portrait">{sprite?<img src={sprite} alt=""/>:icon}<span>{side==='hero'?'YOU':'HOSTILE'}</span></div><div className="unitInfo"><small>{subtitle}</small><h3>{name}</h3><div className="bar"><i style={{width:`${Math.max(0,hp/max*100)}%`}}/><b>{Math.max(0,Math.round(hp))} / {max}</b></div>{shield>0&&<p>⬡ {shield} shield</p>}</div></article>}
function Loadout({run}:{run:RunState}){const h=run.hero!;const synergies=activeSynergies(h);return <div className="loadout"><p className="eyebrow">Current build</p><h2>{CLASSES[h.classId].name}</h2><div className="statGrid">{[['HP',`${Math.round(h.hp)} / ${h.maxHp}`],['Attack',h.attack],['Defense',h.defense],['Speed',h.speed.toFixed(2)],['Crit',`${Math.round(h.crit*100)}%`],['Gold',h.gold]].map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div><h3>Equipment</h3><div className="gearGrid">{['Weapon','Helmet','Armor','Boots','Trinket','Relic'].map(slot=>{const i=h.gear.find(x=>x.slot===slot);return <article key={slot} className={i?.rarity||''}><small>{slot}{i?.set?` · ${i.set}`:''}</small><b>{i?.name||'Empty slot'}</b><em>{i?(i.stat==='speed'?`+${Math.round(i.value*100)}% speed`:`+${i.value} ${i.stat}`):'—'}</em>{i?.effect&&<p className="itemEffect">{i.effect.description}</p>}{i?.curse&&<p className="curseTag">CURSE · {i.curse}</p>}</article>})}</div><h3>Build synergies</h3><div className="synergyGrid">{synergies.map(s=><article key={s.name} className={s.active?'active':''}><small>{s.active?'ACTIVE':'INACTIVE'}</small><b>{s.name}</b><p>{s.detail}</p></article>)}</div><button className="primary" onClick={()=>location.reload()}>Return to expedition</button></div>}
function LeagueHub(){const[state,setState]=useState<any>(undefined);useEffect(()=>{fetchLeagueState().then(s=>setState(s??null))},[]);
 if(state===undefined)return <InfoPage eyebrow="Private league" title="League Hub" intro="Contacting the league office…"><div className="placeholderGrid"><article><small>PLEASE WAIT</small><h3>Loading standings…</h3><p>Fetching the weekly dungeon and leaderboard.</p></article></div></InfoPage>;
 const configured=!!(state&&state.configured);const wc=state?.weeklyChallenge;const lb:any[]=state?.leaderboard||[];const recent:any[]=state?.recentRuns||[];
 return <InfoPage eyebrow="Private league" title="League Hub" intro={configured?'Live standings from the league backend.':'League backend not configured yet — local expeditions continue.'}>
  <div className="placeholderGrid">
   <article><small>WEEKLY DUNGEON</small><h3>{wc?.name||'Waiver Wire Madness'}</h3><p>{wc?.modifier||'One extra reroll token.'}{wc?.featuredBoss?` · Boss: ${wc.featuredBoss}`:''}</p></article>
   <article><small>LEADERBOARD · THIS WEEK</small>{lb.length?<ol className="lbList">{lb.map((e,i)=><li key={i}><b>{e.manager}</b><span>Floor {e.floor} · {e.status==='victory'?'Cleared':'Fell'} · {e.score} pts</span></li>)}</ol>:<><h3>Awaiting submissions</h3><p>{configured?'No runs logged this week yet — be the first.':'Supabase persistence is not configured.'}</p></>}</article>
   <article><small>RECENT RUNS</small>{recent.length?<ul className="lbList">{recent.map((r,i)=><li key={i}><b>{r.manager}</b><span>{CLASSES[r.classId as ClassId]?.name||r.classId} · Floor {r.floor} · {r.status}</span></li>)}</ul>:<><h3>Locker room empty</h3><p>Completed runs will appear here.</p></>}</article>
  </div>
 </InfoPage>;}
function AchievementsPage({earned}:{earned:string[]}){const[feed,setFeed]=useState<any[]|undefined>(undefined);useEffect(()=>{fetchLeagueState().then(s=>setFeed(s?.achievementFeed||[]))},[]);
 const nameFor=(id:string)=>achievements.find(a=>a.id===id)?.name||id;const count=earned.length;
 return <InfoPage eyebrow="Manager legacy" title="Achievement gallery" intro={`Some are triumphs. Others merely prove that witnesses were present. Unlocked ${count} / ${achievements.length}.`}>
  <div className="achievementGrid">{achievements.map(a=>{const on=earned.includes(a.id);return <article className={on?'unlocked':''} key={a.id}><i>{a.icon}</i><small>{on?'UNLOCKED':'LOCKED'}</small><h3>{a.name}</h3><p>{a.detail}</p></article>})}</div>
  {feed&&feed.length>0&&<><h2 className="feedHead">Recent league unlocks</h2><ul className="lbList">{feed.map((f,i)=><li key={i}><b>{f.manager}</b><span>{nameFor(f.achievementId)}</span></li>)}</ul></>}
 </InfoPage>;}
