import {useEffect,useRef,useState} from 'react';
import {BALANCE,BOSSES,BUFFS,CLASSES,FLOORS} from './data';
import {activeSynergies,advance,applyReward,buyShop,enemyFor,heroFor,initial,load,loadEarned,rerollRewards,save,saveEarned,shopCosts,shopOffer,tick} from './engine';
import type{ClassId,RunState}from'./types';
import {achievements} from './config/achievements';
import {submitRun,fetchLeagueState,postAchievement} from './api';

const fmt=(seconds:number)=>`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
export default function App(){const[run,setRun]=useState<RunState>(()=>load()||initial);const[name,setName]=useState('');const[debug,setDebug]=useState(true);const[tab,setTab]=useState<'expedition'|'loadout'|'log'>('expedition');
 useEffect(()=>{const id=setInterval(()=>setRun(s=>tick(s)),BALANCE.tickMs);return()=>clearInterval(id)},[]);useEffect(()=>save(run),[run]);
 const submitted=useRef<number|null>(null);const[submitState,setSubmitState]=useState<'idle'|'sending'|'saved'|'offline'>('idle');
 useEffect(()=>{if(run.screen==='summary'&&run.hero&&submitted.current!==run.seed){submitted.current=run.seed;setSubmitState('sending');submitRun(run).then(r=>setSubmitState(r?.persisted?'saved':'offline'));}},[run.screen,run.seed]);
 const[earned,setEarned]=useState<string[]>(()=>loadEarned());
 useEffect(()=>{if(!run.hero)return;const fresh=run.achievements.filter(id=>!earned.includes(id));if(!fresh.length)return;const next=[...earned,...fresh];setEarned(next);saveEarned(next);const who=run.hero.name;fresh.forEach(id=>postAchievement(who,id));},[run.achievements.length]);
 const chooseClass=(id:ClassId)=>setRun(s=>({...s,hero:heroFor(name.trim()||'Anonymous Menace',id),screen:'buff'}));
 const startBuff=(b:typeof BUFFS[number])=>setRun(s=>{const n=structuredClone(s),h=n.hero!;h.buffs.push(b.title);if(b.kind==='attack')h.attack=Math.round(h.attack*(1+b.amount));if(b.kind==='maxHp'){h.maxHp+=b.amount;h.hp=h.maxHp}if(b.kind==='speed')h.speed+=b.amount;if(b.kind==='defense'){h.defense+=b.amount;h.gold+=20}if(b.kind==='gold'){h.gold+=b.amount;h.rerolls++}n.enemy=enemyFor(1,1,h);n.screen='battle';n.log=[`You enter ${FLOORS[0]}. Nobody has read the waiver.`];return n});
 if(run.screen==='menu')return <Shell onNav={screen=>setRun({...run,screen})}><div className="hero"><div className="crest">D<span>XVIII</span></div><p className="eyebrow">A fantasy league roguelite</p><h1>THE DESCENT</h1><p className="lede">Eighteen floors. One roster. Absolutely no responsible decisions.</p><button className="primary" onClick={()=>setRun({...initial,screen:'name',seed:Date.now()})}>Begin the descent <b>→</b></button>{load()?.hero&&<button className="ghost" onClick={()=>setRun(load()!)}>Continue run · Floor {load()!.floor}</button>}<p className="fine">AUTO-BATTLE · PERMADEATH · QUESTIONABLE TRADES</p></div></Shell>;
 if(run.screen==='achievements')return <Shell onNav={screen=>setRun({...run,screen})}><AchievementsPage earned={earned}/></Shell>;
 if(run.screen==='league')return <Shell onNav={screen=>setRun({...run,screen})}><LeagueHub/></Shell>;
 if(run.screen==='settings')return <Shell onNav={screen=>setRun({...run,screen})}><InfoPage eyebrow="Accessibility & saves" title="Settings" intro="Your expedition autosaves locally after every state change."><div className="settingsCard"><label><span>Reduced motion</span><input type="checkbox" onChange={e=>document.documentElement.classList.toggle('reduced',e.target.checked)}/></label><label><span>Balance telemetry</span><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/></label><button className="danger" onClick={()=>{localStorage.removeItem('descent.run');setRun(initial)}}>Reset local save</button></div></InfoPage></Shell>;
 if(run.screen==='name')return <Shell><Setup step="01 / 03" title="Name your manager" sub="This will be carved into the leaderboard—or the injury report."><input autoFocus maxLength={24} placeholder="Manager name" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&name.trim()&&setRun({...run,screen:'class'})}/><button className="primary" disabled={!name.trim()} onClick={()=>setRun({...run,screen:'class'})}>Choose your class →</button></Setup></Shell>;
 if(run.screen==='class')return <Shell><Setup step="02 / 03" title="Choose your archetype" sub="Your class shapes the build. The dungeon shapes your obituary."><div className="classGrid">{Object.entries(CLASSES).map(([id,c])=><button className="classCard" key={id} onClick={()=>chooseClass(id as ClassId)}><i>{c.icon}</i><div><h3>{c.name}</h3><small>{c.tag}</small><p>{c.desc}</p><em>{c.ability}</em></div></button>)}</div></Setup></Shell>;
 if(run.screen==='buff')return <Shell><Setup step="03 / 03" title="Pick your opening edge" sub="Three gifts from the draft gods. Terms and conditions are mostly curses."><div className="buffGrid">{BUFFS.slice(0,3).map((b,i)=><button className="buffCard" key={b.title} onClick={()=>startBuff(b)}><span>0{i+1}</span><h3>{b.title}</h3><p>{b.detail}</p><b>Take this edge →</b></button>)}</div></Setup></Shell>;
 if(run.screen==='reward'){const h=run.hero!;const cost=shopCosts(run.floor);const offer=shopOffer(run);return <GameFrame run={run} tab={tab} setTab={setTab}><section className="reward"><p className="eyebrow">Checkpoint secured</p><h2>Choose what survives with you</h2><p>The rest goes back on waivers. Then spend your gold before it spends you.</p><div className="rewardGrid">{run.rewards.map(r=><button key={r.id} className={`rewardCard ${r.item?.rarity||''}`} onClick={()=>setRun(applyReward(run,r))}><span>{r.item?.rarity||'BUILD REWARD'}</span><div className="rewardIcon">{r.item?.rarity==='Mythic'?'✺':r.item?.rarity==='Legendary'?'♛':r.kind==='gear'?'◇':r.kind==='heal'?'✚':r.kind==='defense'?'⬡':'↗'}</div><h3>{r.title}</h3><p>{r.detail}</p>{r.item?.curse&&<em className="curseTag">CURSE · {r.item.curse}</em>}<b>Claim reward</b></button>)}</div><button className="reroll" disabled={!h.rerolls} onClick={()=>setRun(rerollRewards(run))}>⟳ Reroll rewards ({h.rerolls})</button><aside className="shop"><header><div><p className="eyebrow">The between-period shop</p><h3>Spend it or die rich</h3></div><b>◈ {h.gold} gold</b></header><div className="shopGrid"><button disabled={h.gold<cost.heal||h.hp>=h.maxHp} onClick={()=>setRun(buyShop(run,'heal'))}><span>✚</span><div><b>Bench Medic</b><small>Restore 28% HP</small></div><em>{cost.heal}g</em></button><button disabled={h.gold<cost.reroll} onClick={()=>setRun(buyShop(run,'reroll'))}><span>⟳</span><div><b>Waiver Token</b><small>+1 reroll</small></div><em>{cost.reroll}g</em></button><button className={offer.rarity} disabled={h.gold<cost.item} onClick={()=>setRun(buyShop(run,'item'))}><span>◇</span><div><b>{offer.name}</b><small>{offer.rarity} {offer.slot}</small></div><em>{cost.item}g</em></button></div></aside></section></GameFrame>;}
 if(run.screen==='summary')return <Shell><div className="summary"><p className="eyebrow">Run {run.won?'cleared':'complete'}</p><h1>{run.won?'The bylaws are broken.':'Mathematically eliminated.'}</h1><div className="summaryStats"><span>Manager<b>{run.hero?.name}</b></span><span>Class<b>{run.hero&&CLASSES[run.hero.classId].name}</b></span><span>Floor reached<b>{run.floor} / 18</b></span><span>Run time<b>{fmt(run.telemetry.elapsed)}</b></span></div><p>{run.won?'The Final Commissioner has been overruled. Your build was disgusting. Compliment intended.':`Your projections ended in ${FLOORS[run.floor-1]}. The waiver wire offers no condolences.`}</p><p className="fine">{submitState==='sending'?'Submitting to the league…':submitState==='saved'?'Logged to the league leaderboard.':submitState==='offline'?'League offline — run saved locally only.':''}</p><button className="primary" onClick={()=>{localStorage.removeItem('descent.run');setRun({...initial,screen:'name',seed:Date.now()})}}>Descend again →</button></div></Shell>;
 const h=run.hero!,e=run.enemy!;const playerDps=h.attack*h.speed*(1+h.crit*.7)+(h.attack*2.25/8);const enemyDps=Math.max(1,e.attack*100/(100+h.defense*7))*e.speed;const ttk=e.hp/playerDps, survival=(h.hp+h.shield)/enemyDps;
 return <GameFrame run={run} tab={tab} setTab={setTab}><main className="battle"><section className="floorHead"><div><p className="eyebrow">Floor {String(run.floor).padStart(2,'0')} · Encounter {run.encounter}/{BALANCE.encountersPerFloor}</p><h2>{FLOORS[run.floor-1]}</h2><p>Where projections come to become regrets.</p></div><div className="floorPips">{FLOORS.map((_,i)=><i key={i} className={i<run.floor?'done':i===run.floor-1?'now':''}/>)}</div></section>
 <section className="arena"><Combatant side="hero" icon={CLASSES[h.classId].icon} name={h.name} subtitle={CLASSES[h.classId].name} hp={h.hp} max={h.maxHp} shield={h.shield}/><div className="versus"><b>VS</b><span>{fmt(run.telemetry.encounterElapsed)}</span></div><Combatant side="enemy" icon={e.boss?'♛':'☠'} name={e.name} subtitle={e.boss?'Floor boss · Elite':'Dungeon resident'} hp={e.hp} max={e.maxHp}/></section>
 {e.boss&&<aside className="warning"><b>⚠ {BOSSES[run.floor]?.mechanic}</b><span>{BOSSES[run.floor]?.intro}</span></aside>}
 <section className="lower"><div className="ability"><div className="abilityIcon">{CLASSES[h.classId].icon}</div><div><small>AUTOMATIC ABILITY</small><h3>{CLASSES[h.classId].ability.split(':')[0]}</h3><p>{CLASSES[h.classId].ability.split(':')[1]}</p></div><div className="cooldown"><span style={{'--p':`${Math.min(100,run.abilityClock/8*100)}%`} as React.CSSProperties}/><b>{Math.max(0,8-run.abilityClock).toFixed(1)}s</b></div></div><div className="log"><header><b>Combat feed</b><span>LIVE</span></header>{run.log.slice(0,5).map((l,i)=><p key={i} className={l.includes('⚠')?'alert':''}>{l}</p>)}</div></section>
 {debug&&<section className="debug"><header><b>⌁ Balance telemetry</b><button onClick={()=>setDebug(false)}>×</button></header><div>{[['Player DPS',playerDps.toFixed(1)],['Enemy DPS',enemyDps.toFixed(1)],['Est. time to kill',`${ttk.toFixed(1)}s`],['Est. survival',`${survival.toFixed(1)}s`],['Run duration',fmt(run.telemetry.elapsed)],['Recent damage',String(run.telemetry.damage.reduce((a,b)=>a+b,0))],['Recent healing',String(run.telemetry.healing.reduce((a,b)=>a+b,0))],['Difficulty',`${(Math.pow(1+BALANCE.enemyAttackPerFloor,run.floor-1)*100).toFixed(0)}%`]].map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div></section>}
 </main></GameFrame>;
}
function Shell({children,onNav}:{children:React.ReactNode;onNav?:(screen:'menu'|'achievements'|'settings'|'league')=>void}){return <div className="shell"><header className="top"><button className="wordmark" onClick={()=>onNav?.('menu')}>THE <span>DESCENT</span></button><nav><button onClick={()=>onNav?.('achievements')}>Achievements</button><button onClick={()=>onNav?.('league')}>League Hub</button><button onClick={()=>onNav?.('settings')}>Settings</button></nav></header>{children}<footer>NO PRIZES · NO MERCY · AUTOSAVES LOCALLY</footer></div>}
function InfoPage({eyebrow,title,intro,children}:{eyebrow:string;title:string;intro:string;children:React.ReactNode}){return <main className="infoPage"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p>{children}</main>}
function Setup({step,title,sub,children}:{step:string,title:string,sub:string,children:React.ReactNode}){return <div className="setup"><p className="eyebrow">Expedition setup · {step}</p><h1>{title}</h1><p>{sub}</p>{children}</div>}
function GameFrame({run,tab,setTab,children}:{run:RunState;tab:'expedition'|'loadout'|'log';setTab:(v:'expedition'|'loadout'|'log')=>void;children:React.ReactNode}){const newRun=()=>{if(!window.confirm('Abandon the current run and start a new one?'))return;localStorage.removeItem('descent.run');location.reload()};return <div className="game"><header className="gameTop"><b>THE <span>DESCENT</span></b><div className="runmeta"><span>Floor<b>{run.floor} / 18</b></span><span>Encounter<b>{run.encounter} / {BALANCE.encountersPerFloor}</b></span><span>Run time<b>{fmt(run.telemetry.elapsed)}</b></span></div><div className="currencies"><span>◈ {run.hero?.gold}</span><span>✦ {run.hero?.essence}</span><span>⟳ {run.hero?.rerolls}</span></div><button className="newRunButton" onClick={newRun}>New run</button></header><nav className="tabs">{(['expedition','loadout','log'] as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>{tab==='expedition'?children:tab==='loadout'?<Loadout run={run}/>:<div className="fullLog"><h2>Expedition log</h2>{run.log.map((l,i)=><p key={i}>{l}</p>)}</div>}</div>}
function Combatant({side,icon,name,subtitle,hp,max,shield=0}:{side:string;icon:string;name:string;subtitle:string;hp:number;max:number;shield?:number}){return <article className={`combatant ${side}`}><div className="portrait">{icon}<span>{side==='hero'?'YOU':'HOSTILE'}</span></div><div className="unitInfo"><small>{subtitle}</small><h3>{name}</h3><div className="bar"><i style={{width:`${Math.max(0,hp/max*100)}%`}}/><b>{Math.max(0,Math.round(hp))} / {max}</b></div>{shield>0&&<p>⬡ {shield} shield</p>}</div></article>}
function Loadout({run}:{run:RunState}){const h=run.hero!;const synergies=activeSynergies(h);return <div className="loadout"><p className="eyebrow">Current build</p><h2>{CLASSES[h.classId].name}</h2><div className="statGrid">{[['HP',`${Math.round(h.hp)} / ${h.maxHp}`],['Attack',h.attack],['Defense',h.defense],['Speed',h.speed.toFixed(2)],['Crit',`${Math.round(h.crit*100)}%`],['Gold',h.gold]].map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div><h3>Equipment</h3><div className="gearGrid">{['Weapon','Helmet','Armor','Boots','Trinket','Relic'].map(slot=>{const i=h.gear.find(x=>x.slot===slot);return <article key={slot} className={i?.rarity||''}><small>{slot}{i?.set?` · ${i.set}`:''}</small><b>{i?.name||'Empty slot'}</b><em>{i?(i.stat==='speed'?`+${Math.round(i.value*100)}% speed`:`+${i.value} ${i.stat}`):'—'}</em>{i?.effect&&<p className="itemEffect">{i.effect.description}</p>}{i?.curse&&<p className="curseTag">CURSE · {i.curse}</p>}</article>})}</div><h3>Build synergies</h3><div className="synergyGrid">{synergies.map(s=><article key={s.name} className={s.active?'active':''}><small>{s.active?'ACTIVE':'INACTIVE'}</small><b>{s.name}</b><p>{s.detail}</p></article>)}</div><button className="primary" onClick={()=>location.reload()}>Return to expedition</button></div>}
function LeagueHub(){const[state,setState]=useState<any>(undefined);useEffect(()=>{fetchLeagueState().then(s=>setState(s??null))},[]);
 if(state===undefined)return <InfoPage eyebrow="Private league" title="League Hub" intro="Contacting the league office…"><div className="placeholderGrid"><article><small>PLEASE WAIT</small><h3>Loading standings…</h3><p>Fetching the weekly dungeon and leaderboard.</p></article></div></InfoPage>;
 const configured=!!(state&&state.configured);const wc=state?.weeklyChallenge;const lb:any[]=state?.leaderboard||[];const recent:any[]=state?.recentRuns||[];
 return <InfoPage eyebrow="Private league" title="League Hub" intro={configured?'Live standings from the league backend.':'League backend not configured yet — local expeditions continue.'}>
  <div className="placeholderGrid">
   <article><small>WEEKLY DUNGEON</small><h3>{wc?.name||'Waiver Wire Madness'}</h3><p>{wc?.modifier||'One extra reroll token.'}{wc?.featuredBoss?` · Boss: ${wc.featuredBoss}`:''}</p></article>
   <article><small>LEADERBOARD · THIS WEEK</small>{lb.length?<ol className="lbList">{lb.map((e,i)=><li key={i}><b>{e.manager}</b><span>Floor {e.floor} · {e.status==='victory'?'Cleared':'Fell'} · {e.score} pts</span></li>)}</ol>:<><h3>Awaiting submissions</h3><p>{configured?'No runs logged this week yet — be the first.':'Supabase persistence is not configured.'}</p></>}</article>
   <article><small>RECENT RUNS</small>{recent.length?<ul className="lbList">{recent.map((r,i)=><li key={i}><b>{r.manager}</b><span>{CLASSES[r.classId as ClassId]?.name||r.classId} · Floor {r.floor} · {r.status}</span></li>)}</ul>:<><h3>Locker room empty</h3><p>Completed runs will appear here.</p></>}</article>
  </div>
 </InfoPage>;}
function AchievementsPage({earned}:{earned:string[]}){const[feed,setFeed]=useState<any[]|undefined>(undefined);useEffect(()=>{fetchLeagueState().then(s=>setFeed(s?.achievementFeed||[]))},[]);
 const nameFor=(id:string)=>achievements.find(a=>a.id===id)?.name||id;const count=earned.length;
 return <InfoPage eyebrow="Manager legacy" title="Achievement gallery" intro={`Some are triumphs. Others merely prove that witnesses were present. Unlocked ${count} / ${achievements.length}.`}>
  <div className="achievementGrid">{achievements.map(a=>{const on=earned.includes(a.id);return <article className={on?'unlocked':''} key={a.id}><i>{a.icon}</i><small>{on?'UNLOCKED':'LOCKED'}</small><h3>{a.name}</h3><p>{a.detail}</p></article>})}</div>
  {feed&&feed.length>0&&<><h2 className="feedHead">Recent league unlocks</h2><ul className="lbList">{feed.map((f,i)=><li key={i}><b>{f.manager}</b><span>{nameFor(f.achievementId)}</span></li>)}</ul></>}
 </InfoPage>;}
